project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    website:
    contents:
      - index.ipynb
      - section: Lessons
        contents:
        - 01_PyTorch_Basics.ipynb
        - 02_Optimization.ipynb
        - 03_Building_NNs.ipynb
        - 04_Representations.ipynb
        - 05_CLIP.ipynb
        - 06_generative_1.ipynb
        - 07_GAN1.ipynb
        - 08_GAN2.ipynb
        - 09_sequence_1.ipynb
        - 10_transformers.ipynb
        - 11_sequence_3.ipynb
        - 12_DM1.ipynb
        - 13_DM2.ipynb
        - 14_DM3.ipynb
      - section: Bonus Material
        contents:
        - 60_Bonus_Material_Intro.ipynb
        - 61_Datasets.ipynb
        - 30_ethics.ipynb
      - 40_Discussions.ipynb
      - 90_Projects.ipynb

metadata-files: [nbdev.yml]