# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/genai/',
                'doc_host': 'https://johnowhitaker.github.io',
                'git_url': 'https://github.com/johnowhitaker/genai/',
                'lib_path': 'genai'},
  'syms': { 'genai.core': { 'genai.core.foo': ('getting.html#foo', 'genai/core.py'),
                            'genai.core.say_hello': ('getting.html#say_hello', 'genai/core.py')},
            'genai.utils': { 'genai.utils.load_image_pil': ('pytorch.html#load_image_pil', 'genai/utils.py'),
                             'genai.utils.pil_to_tensor': ('pytorch.html#pil_to_tensor', 'genai/utils.py'),
                             'genai.utils.tensor_to_pil': ('pytorch.html#tensor_to_pil', 'genai/utils.py')}}}