# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_Getting Started.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../00_Getting Started.ipynb 14
def foo(): pass

# %% ../00_Getting Started.ipynb 15
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
