# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_PyTorch Basics.ipynb.

# %% auto 0
__all__ = ['test_export_fn', 'load_image_pil', 'pil_to_tensor']

# %% ../01_PyTorch Basics.ipynb 2
import torch
import torchvision
from PIL import Image
import numpy as np

# %% ../01_PyTorch Basics.ipynb 10
def test_export_fn():
    print('Hello World')
    
def load_image_pil(fn, size=None):
    im = Image.open(fn).convert('RGB')
    if size != None:
        im = im.resize(size)
    return im

def pil_to_tensor(im):
    return torch.tensor(np.array(im)).permute(2, 0, 1)/255.0
