# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tgl_course/',
                'doc_host': 'https://johnowhitaker.github.io',
                'git_url': 'https://github.com/johnowhitaker/genai/',
                'lib_path': 'tgl_course'},
  'syms': { 'tgl_course.utils': { 'tgl_course.utils.load_image_pil': ('pytorch_basics.html#load_image_pil', 'tgl_course/utils.py'),
                                  'tgl_course.utils.pil_to_tensor': ('pytorch_basics.html#pil_to_tensor', 'tgl_course/utils.py'),
                                  'tgl_course.utils.tensor_to_pil': ('pytorch_basics.html#tensor_to_pil', 'tgl_course/utils.py')}}}