# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tglcourse/',
                'doc_host': 'https://johnowhitaker.github.io',
                'git_url': 'https://github.com/johnowhitaker/tglcourse/',
                'lib_path': 'tglcourse'},
  'syms': { 'tglcourse.data_utils': { 'tglcourse.data_utils.get_mnist_dl': ('datasets.html#get_mnist_dl', 'tglcourse/data_utils.py'),
                                      'tglcourse.data_utils.mnist_transform': ('datasets.html#mnist_transform', 'tglcourse/data_utils.py')},
            'tglcourse.utils': { 'tglcourse.utils.load_image_pil': ('pytorch_basics.html#load_image_pil', 'tglcourse/utils.py'),
                                 'tglcourse.utils.pil_to_tensor': ('pytorch_basics.html#pil_to_tensor', 'tglcourse/utils.py'),
                                 'tglcourse.utils.tensor_to_pil': ('pytorch_basics.html#tensor_to_pil', 'tglcourse/utils.py')}}}